// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package support_api

import (
	"github.com/A-SoulFan/acao-homework/internal/app/support_api/server/gin"
	"github.com/A-SoulFan/acao-homework/internal/app/support_api/server/gin/handler"
	"github.com/A-SoulFan/acao-homework/internal/app/support_api/server/gin/middleware"
	"github.com/A-SoulFan/acao-homework/internal/app/support_api/server/gin/router"
	"github.com/A-SoulFan/acao-homework/internal/app/support_api/server/task"
	"github.com/A-SoulFan/acao-homework/internal/app/support_api/service"
	"github.com/A-SoulFan/acao-homework/internal/app/support_api/service/banner"
	"github.com/A-SoulFan/acao-homework/internal/app/support_api/service/member"
	"github.com/A-SoulFan/acao-homework/internal/app/support_api/service/milestone"
	"github.com/A-SoulFan/acao-homework/internal/app/support_api/service/recommend"
	"github.com/A-SoulFan/acao-homework/internal/app/support_api/service/stroll"
	"github.com/A-SoulFan/acao-homework/internal/app/support_api/service/team"
	"github.com/A-SoulFan/acao-homework/internal/pkg/cache"
	"github.com/A-SoulFan/acao-homework/internal/pkg/config"
	"github.com/A-SoulFan/acao-homework/internal/pkg/database"
	"github.com/A-SoulFan/acao-homework/internal/pkg/log"
	"github.com/A-SoulFan/acao-homework/internal/pkg/transports/http"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitApp(configFile config.Path) (*App, error) {
	viper, err := config.New(configFile)
	if err != nil {
		return nil, err
	}
	options, err := log.NewOptions(viper)
	if err != nil {
		return nil, err
	}
	logger, err := log.NewLogger(options)
	if err != nil {
		return nil, err
	}
	httpOptions, err := http.NewOptions(viper, logger)
	if err != nil {
		return nil, err
	}
	errorInterceptor := middleware.NewErrorInterceptor(logger)
	databaseOptions, err := database.NewOptions(viper, logger)
	if err != nil {
		return nil, err
	}
	db, err := database.NewDatabase(databaseOptions)
	if err != nil {
		return nil, err
	}
	strollService := stroll.NewDefaultStrollService(logger, db)
	handlerStroll := handler.NewStrollApi(strollService)
	milestoneService := milestone.NewDefaultMilestoneService(logger, db)
	handlerMilestone := handler.NewMilestoneApi(milestoneService)
	recommendService := recommend.NewDefaultRecommendService(logger)
	handlerRecommend := handler.NewRecommendApi(recommendService)
	bannerService := banner.NewDefaultBannerService(db)
	handlerBanner := handler.NewBannerApi(bannerService)
	memberService := member.NewDefaultMemberService(db)
	handlerMember := handler.NewMemberApi(memberService)
	teamService := team.NewDefaultTeamService(db)
	handlerTeam := handler.NewTeamApi(teamService)
	initRouters := router.InitRouter(errorInterceptor, handlerStroll, handlerMilestone, handlerRecommend, handlerBanner, handlerMember, handlerTeam)
	engine := http.NewRouter(httpOptions, logger, initRouters)
	server, err := http.NewServer(httpOptions, logger, engine)
	if err != nil {
		return nil, err
	}
	ginServer := gin.NewServer(logger, server)
	app := NewApp(ginServer, recommendService, milestoneService, strollService)
	return app, nil
}

// wire.go:

var providerSet = wire.NewSet(config.ProviderSet, http.ProviderSet, log.ProviderSet, database.ProviderSet, cache.ProviderSet, middleware.NewErrorInterceptor, handler.ProviderSet, service.ProviderSet, router.InitRouter, gin.ProviderSet, task.ProviderSet, NewApp)
